services:
  apache:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.apache
      args:
        STUDENTS: ${STUDENTS}
        TEACHERS: ${TEACHERS}
    environment:
      - STUDENTS=${STUDENTS}
      - TEACHERS=${TEACHERS}
    container_name: apache
    volumes:
      - html:/var/www/html
      - home:/home
    ports:
      - "80:80"
      - "22:22"
    networks:
      - network
    depends_on:
      - mariadb
      - phpmyadmin

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: mydatabase
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    volumes:
      - database:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - network
    depends_on:
      - mariadb

volumes:
  html:
  database:
  home:

networks:
  network:
    driver: bridge
